Custom Events Limiter
newrelic/go-agent pull request #524
Opened 2022-06-27 19:34 UTC by mirackara

## Links

## Details

2022-06-27 19:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/go-agent?pullRequest=524) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/go-agent?pullRequest=524) before we can accept your contribution.<br/><hr/>**Mirac Kara** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/go-agent?pullRequest=524) it.</sub>

2022-06-28 21:18 UTC, nr-swilloughby approved these changes, later dismissed

2022-06-29 16:01 UTC, iamemilio commented
This seems to be causing a number of the legacy tests to fail, which it should not effect. I think we should get to the bottom of why that is happening before we merge anything.

2022-06-29 16:03 UTC, iamemilio requested changes
This seems to be causing a number of the legacy tests to fail, which it should not effect. I think we should get to the bottom of why that is happening before we merge anything.

I noticed that some of your changes altered internal, rather than v3/internal. I suspect that a lot of your trouble is coming from that change.

2022-06-29 16:11 UTC, nr-swilloughby commented
Good catch!

2022-06-29 16:38 UTC, mirackara commented
Legacy tests are now good. Looks like some more of the v3 tests are failing however. Thanks for the comment!

2022-06-29 16:54 UTC, RichVanderwal commented
Thanks for looking at how the other agents are configured when you were naming this option!

2022-06-29 19:44 UTC, iamemilio submitted a review, later dismissed

2022-06-29 20:00 UTC, iamemilio approved these changes

2022-06-29 20:02 UTC, merged