Nrredis v9
newrelic/go-agent pull request #658
Opened 2023-03-30 17:51 UTC by iamemilio

Submitting on behalf of @gunturaf. We merged the PR into master instead of develop, and had to undo. Merged PR's cannot be re-opened. 

Author: @gunturaf

2023-03-30 18:02 UTC, iamemilio commented
@gunturaf it looks like a number of valid failures occurred in the tests. Sorry about this, but would you mind taking a look and seeing if there are any implementation gaps that may be causing this?

2023-03-30 23:12 UTC, gunturaf commented
Alright, checking @iamemilio

2023-03-31 21:21 UTC, gunturaf requested changes

2023-03-31 21:21 UTC, gunturaf commented on v3/integrations/nrredis-v9/nrredis.go
> +		if host != "" {
```suggestion
		if host == "" {
```
My bad, this should have been an equality check.
I've tested the edit on my local go 1.20.2 and the test should work.

2023-04-03 18:17 UTC, iamemilio commented
Something seems to be wrong with GH actions. Closing and re-opening to attempt a fix.

2023-04-12 07:47 UTC, gunturaf commented
@iamemilio can we get an ETA for this?

2023-04-14 17:20 UTC, iamemilio commented
This is a priority for our next release. We're doing our best to get it merged, but we have been having difficulties with our CI.

2023-04-24 20:07 UTC, iamemilio commented
Rebased on develop latest, hopefully this will fix the tests

2023-04-26 15:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/go-agent?pullRequest=658) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/go-agent?pullRequest=658) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: iamemilio<br/>:x: gunturaf<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/go-agent?pullRequest=658) it.</sub>

2023-04-27 08:48 UTC, gunturaf commented
I think you should sign the CLA to fix this pipeline @iamemilio ?

2023-04-27 16:57 UTC, nr-swilloughby approved these changes
LGTM

2023-04-27 19:38 UTC, merged