adding LICENSE.txt so the doc should be shown at pkg.go.dev
newrelic/go-agent pull request #661
Opened 2023-04-05 03:13 UTC by egon12

In https://pkg.go.dev/github.com/newrelic/go-agent/v3/integrations/nrpgx5 we got report that 
The docs is not shown because `License: None detected not legal advice `

In it's siblings folder https://pkg.go.dev/github.com/newrelic/go-agent/v3/integrations/nrpgx, there are already license
So the documentation is shown perfectly.

This commit will add the license so we can see the documentation in pkg.go.dev

## Links

## Details

2023-04-05 14:12 UTC, iamemilio approved these changes

2023-04-07 18:27 UTC, iamemilio requested changes
Can you rebase this PR from the develop branch. There are some revert commits in master that are not in develop and they are causing all sorts of trouble. We are working on resolving that.

2023-04-19 01:23 UTC, egon12 commented
Sorry I miss the message. I've rebased it into develop, and push force into it.

2023-04-20 18:05 UTC, iamemilio approved these changes

2023-04-20 18:05 UTC, mirackara approved these changes

2023-04-20 18:05 UTC, merged