Disable IAST if HighSecurity is enabled
newrelic/go-agent pull request #727
Opened 2023-06-07 12:06 UTC by aayush-ap

Disabling IAST if HighSecurity is enabled because in HighSecurity mode request parameters can't be collected and without request parameters, IAST won't be able to work properly.

reference: https://docs.newrelic.com/docs/apm/agents/go-agent/configuration/go-agent-configuration/#high_security

Disabling IAST if HighSecurity is enabled

2023-06-07 12:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/go-agent?pullRequest=727) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/go-agent?pullRequest=727) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/go-agent?pullRequest=727) it.</sub>

2023-06-07 23:49 UTC, nr-swilloughby requested changes
Looks good but can you sign the contributor license agreement so that check can be cleared?
Thanks

2023-06-08 04:03 UTC, aayush-ap commented
> Looks good but can you sign the contributor license agreement so that check can be cleared? Thanks

Sure

2023-06-08 15:05 UTC, nr-swilloughby approved these changes

2023-06-08 15:05 UTC, merged