Cloud Services Entity Relationship Changes
newrelic/go-agent pull request #952
Opened 2024-08-21 21:07 UTC by mirackara

2024-09-06 17:34 UTC, nr-swilloughby commented on v3/integrations/nramqp/nramqp.go
> +		return "", ""
I thought the user:password@ part of the uri was optional. Should we consider the case of "amqp://host:port" here instead of returning empty strings?

2024-09-06 17:36 UTC, nr-swilloughby requested changes
just one question about uri format

2024-10-10 19:34 UTC, nr-swilloughby approved these changes

2024-10-10 20:07 UTC, iamemilio approved these changes

2024-10-10 20:07 UTC, merged